### ISSUE TITLE
Remove the use of non-inclusive terms

### ISSUE THREAD

**Issue by lodi-g** [facebookexperimental/rome#110]
There is two non-inclusive words on master branch: 'whitelist' and 'blacklist'.
I think they are not inclusive and should be replaced by 'allow-list' and 'disallow-list' or some equivalent.

https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-compiler/transforms/compile/validation/optimizeImports.ts#L29
https://github.com/facebookexperimental/rome/blob/master/packages/%40romejs/js-parser/xhtmlEntities.ts#L273

Thanks

**Comment by sebmck** [comment]
Thanks for flagging! Happy to accept a PR, otherwise I'll get around to it when I can.  I've avoided blacklist/whitelist in the configuration in favor of `ignore`, `only` etc but this must have slipped through.

We also use the terms `master` and `worker`. Unclear if that's a concern since it's not `master`/`slave` which is the common problematic case.
