### ISSUE TITLE
Codemods

### ISSUE THREAD

**Issue by jedwards1211** [facebookexperimental/rome#208]
If this aims to be a project for all things related to the processing of JavaScript, should it also provide an alternative to JSCodeshift, or perhaps more importantly Recast?

**Comment by sebmck** [comment]
A codemod in the Rome world is just a lint autofix. It's actually better than a codemod, since a codemod is a step you perform only once. At least at Facebook that's problematic that there's always so much code in flight that you need to run the code mod over the following days to make sure you catch all newly committed code. An autofix would allow it to happen automatically. Unclear what this looks like for custom transforms though.

**Comment by jedwards1211** [comment]
Yeah I write a lot of custom transforms these days, and many of them are intended to be manually triggered on a specific file/selection by an IDE command instead of run on a whole codebase, like [material-ui-codemorphs](https://marketplace.visualstudio.com/items?itemName=vscodeshift.material-ui-codemorphs)

**Comment by sebmck** [comment]
Closing since the question has been answered.

**Comment by jedwards1211** [comment]
FWIW, I've been refactoring the codebase of Sequelize to replace promise chains with async/await.  There were too many of them to ever be able to do it all by hand, so I wrote a codemod; however it's impossible to get perfect output with the codemod either, so it had to be a one-time thing followed by manual cleanup.  Some AST transforms don't really want to be lint rules...
