### ISSUE TITLE
Run in Browser?

### ISSUE THREAD

**Issue by curran** [facebookexperimental/rome#213]
Hey! I have a question about the project.

I'm working on an in-browser JavaScript IDE [VizHub](https://vizhub.com/curran/90f961ce0f824558a4cc053bd38ae5f3?edit=files&file=index.js).

Would it be remotely possible to run this toolchain within the browser?

I'm thinking the biggest blocker is extensive use of `require('fs')`.

I'm opening this issue mainly to see if anyone else would be interested in doing this.

Thanks!

**Comment by sebmck** [comment]
> I'm thinking the biggest blocker is extensive use of `require('fs')`.

All file system access happens through the `@romejs/fs` package.

You can individually use each piece of Rome without requiring file access. eg. you can require `@romejs/js-parser` and `@romejs/js-compiler` and call `lint` yourself. But like you mentioned, file system access is required by the server.

I haven't spent a ton of time thinking about it since it hasn't been high priority. I imagine if we eventually want to embed Rome completely on the website as some sort of playground we'll invest time into creating the necessary abstractions.

**Comment by sebmck** [comment]
Closing since the question has been answered.

**Comment by curran** [comment]
Very nice. Thanks for responding!

**Comment by KevinKelbie** [comment]
I got Rome working in the browser and have documented the steps here: https://github.com/KevinKelbie/rome/blob/rome-browserify/browserify.sh but keep in mind its a very hacky approach.

The only line of code I had to manually change was in `packages/@romejs/path/index.ts` where this `os.userInfo().homedir` causes issues.
