### ISSUE TITLE
Lint suggestions

### ISSUE THREAD

**Issue by sebmck** [facebookexperimental/rome#320]
Right now the linter only has one possible autofix. I saw that ESLint added [suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions) which allows for multiple possible fixes.

This is something that we will probably want to add to Rome. This issue tracks the implementation if we decide to add it.

**Comment by ooflorent** [comment]
Suggestions also might be used when the fix is unsafe. For example, since `==` cannot be replaced without strong heuristics, the fix could be a single suggestion.

Another approach might be to tag some fixes as _unsafe_ and apply them only if a flag is provided. Not sure if it’s a good idea though. Definitely not if suggestions are implemented...
