### ISSUE TITLE
Apply suppression to a node

### ISSUE THREAD

**Issue by ooflorent** [facebookexperimental/rome#371]
Currently a suppression is applied to a line. Thanks to this mechanism, the same error could be muted multiple times. For example, the below snippet does not report `any` as error:

```ts
// rome-suppress-next-line lint/noExplicitAny
type SomeStrangeType<U> = U extends any[] ? Array<[U, any]> : Map<U, any[]>;
```

However, we have errors because `noShorthandArrayType` fails for `any[]`. When the fixes are applied, the type is updated and the node is formatted:

```ts
// rome-suppress-next-line lint/noExplicitAny
type SomeStrangeType<U> = U extends Array<any>
  ? Array<[U, any]>
  : Map<U, Array<any>>;
```

Because of the formatting, the second and the last lines are no longer suppressed and the `noExplicitAny` errors are back.

I think that a new type of suppression should be added to Rome to suppress the errors for the entire expression. Ideally this new type should replace `next-line` so the end-user doesn't have to think about what type suppression should be used.

**Comment by sebmck** [comment]
On the surface this seems like a good idea but I'm worried that this will make it extremely easy to suppress errors in big blocks of code. eg. having it attached to a function.

**Comment by sebmck** [comment]
#373 has been merged but I want to leave this open to make sure we're being deliberate. Quoted from that PR:

> 
This PR also implements `rome-ignore-next-statement` that takes the range of the node it's attached to and suppresses everything within it. I'm not 100% sure how I feel about this. It feels very easily abused, or could even accidentally hide new errors unintentionally. We should have a good story if it's actually worth it. If the goal is to make it easier on the developer in the event of formatting causing newlines, then we should invest in some logic to automatically move or add suppressions rather than offering this capability.
